# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main main.go"
# Binary file yields from `cmd`.
bin = "tmp/main"
# Customize binary, can setup environment variables when run your app.
full_bin = "APP_ENV=dev ./tmp/main ui"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "yml", "toml"]
# Ignore these filename extensions or directories.
exclude_dir = ["data", "logs", "bin", "tmp", ".git", "vendor", "node_modules", "internal/web/dist"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = []
# Exclude specific regular expressions.
exclude_regex = ["_test.go"]
# Exclude unchanged files.
exclude_unchanged = false
# Follow symlink for directories
follow_symlink = false
# This log file places in your tmp_dir.
log = "air.log"
# Poll files of changes.
poll = false
# Poll interval (unit: ms).
poll_interval = 0
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt signal before killing process. Only for windows.
send_interrupt = false
# Delay after sending Interrupt signal.
kill_delay = 500 # ms
# Rerun binary or not
rerun = false
# Delay after rerun binary
rerun_delay = 500

[log]
# Show log time
main_only = false
time = false

[color]
# Customize each part's color. If no color found, use the raw log message.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
